-- ======================================================
-- FIX: columna `id` sin autoincremento en universities/scholarships
-- ======================================================
-- Síntoma: POST /rest/v1/universities devuelve 400 Bad Request con
--   "null value in column "id" of relation "universities" violates
--    not-null constraint"
-- Causa: la columna `id` es NOT NULL pero no tiene DEFAULT (no es
--   SERIAL/IDENTITY). El frontend correctamente NO envía `id` en el
--   insert (debe autogenerarse) — Postgres la recibe NULL y falla.
--   El UPDATE nunca toca esta columna, por eso editar sí funcionaba.
-- Fix: convertir `id` en IDENTITY y sincronizar la secuencia interna
--   para que arranque después del id máximo ya existente (evita
--   colisiones con filas migradas previamente).
-- ======================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    WHERE c.relname = 'universities' AND a.attname = 'id' AND a.attidentity <> ''
  ) THEN
    ALTER TABLE universities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('universities', 'id'),
  COALESCE((SELECT MAX(id) FROM universities), 0) + 1,
  false
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    WHERE c.relname = 'scholarships' AND a.attname = 'id' AND a.attidentity <> ''
  ) THEN
    ALTER TABLE scholarships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('scholarships', 'id'),
  COALESCE((SELECT MAX(id) FROM scholarships), 0) + 1,
  false
);

-- ======================================================
-- OPCIONAL / preventivo: solo ejecutar si tras el fix anterior
-- aparece un NUEVO error del tipo:
--   "new row violates row-level security policy for table X" (42501)
-- La migración v2 solo agregó políticas de SELECT público; si el
-- INSERT/UPDATE de administradores dejó de depender de una política
-- creada manualmente en el Dashboard, esto la recrea de forma segura.
-- ======================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can insert universities' AND tablename = 'universities') THEN
    CREATE POLICY "Admins can insert universities" ON universities
      FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can update universities' AND tablename = 'universities') THEN
    CREATE POLICY "Admins can update universities" ON universities
      FOR UPDATE USING (
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can insert scholarships' AND tablename = 'scholarships') THEN
    CREATE POLICY "Admins can insert scholarships" ON scholarships
      FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can update scholarships' AND tablename = 'scholarships') THEN
    CREATE POLICY "Admins can update scholarships" ON scholarships
      FOR UPDATE USING (
        EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
      );
  END IF;
END $$;
